upstream pedidos {
    server servico_pedidos:8001;
}

upstream cardapio {
    server servico_cardapio:8002;
}

upstream notificacoes {
    server servico_notificacoes:8003;
}

server {
    listen 80;

    # Rota para o serviço de pedidos (interface principal)
    location / {
        proxy_pass http://pedidos;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # API de cardápio
    location /api/cardapio/ {
        proxy_pass http://cardapio/api/produtos/;
        proxy_set_header Host $host;
    }

    # API de notificações
    location /api/notificacoes/ {
        proxy_pass http://notificacoes/;
        proxy_set_header Host $host;
    }
}
