# Generated by Django 6.0.5 on 2026-05-16 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('balcao', 'Balcão'), ('entrega', 'Entrega'), ('mesa', 'Mesa')], default='balcao', max_length=20)),
                ('status', models.CharField(choices=[('recebido', 'Recebido'), ('preparando', 'Preparando'), ('pronto', 'Pronto'), ('entregue', 'Entregue')], default='recebido', max_length=20)),
                ('forma_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao', 'Cartão'), ('pix', 'Pix')], default='dinheiro', max_length=20)),
                ('numero_mesa', models.IntegerField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.produto')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='produtos',
            field=models.ManyToManyField(through='pedidos.ItemPedido', to='pedidos.produto'),
        ),
    ]
